version: "3"
services:
  client:
    build:
      context: ./client
      dockerfile: ./local.Dockerfile
    tty: true
    command: npm run serve
    environment:
      - VUE_APP_API_URL=http://server:3030
    ports:
      - 8080:8080
    volumes:
      - ./client/src:/app/src
  server:
    build: ./server
    command: npm run serve
    depends_on:
      - mongodb
    ports:
      - 3030:3030
      - 9999:9999
    volumes:
      - ./server/src:/app/src
      - ./server/public:/app/public
      - ./server/helpers:/app/helpers
      - ./server/config:/app/config
      - ./server/test:/app/test
    environment:
      - NODE_ENV=docker
  mongodb:
    image: mongo:3.6.7
    ports:
      - 27017:27017
    volumes:
       - mongodb-data:/data/db
volumes:
  mongodb-data:
