version: "3"
services:
  client:
    build: ./client
    tty: true
    ports:
      - 80:80
  server:
    build: ./server
    depends_on:
      - mongodb
    ports:
      - 3030:3030
    environment:
      - NODE_ENV=docker
  mongodb:
    image: mongo:3.6.7
    ports:
      - 27017:27017
    volumes:
       - mongodb-data:/data/db
volumes:
  mongodb-data:
